#!/bin/bash
set -e

cd $(dirname $0)/..

. ./scripts/version.sh

TAG=${TAG:-${VERSION_TAG}${SUFFIX}}
REPO=${REPO:-taichikageyama}
IMAGE_NAME=${IMAGE_NAME:-k3s}

IMAGE=${REPO}/${IMAGE_NAME}:${TAG}
cp dist/artifacts/k3s* build/out/k3s
docker build -t ${IMAGE} -f package/Dockerfile.debian .
echo Built ${IMAGE}
